version: '3.2'
services:
  api:
    image: node:14.17.4-alpine3.14
    container_name: nestjs-cars
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    environment:
      #APP
      NODE_ENV: development
      API_HOST: http://localhost:3001
      #DB - local
      POSTGRES_HOST: db
      POSTGRES_DB: sis_cars
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_MAX_CONNECTION: 20
    depends_on:
      - db
    volumes:
      - .:/app
      - ~/.config:/root/.config
      - /node_modules
    ports:
      - '3001:3001'
    expose:
      - 3001
    user: 1000:1000
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sis_cars
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432